version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  read-db:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"