version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  read-db:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"
  event-store:
    image: mongo:6.0.4
    ports:
      - 27019:27017
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro